### PR TITLE
er changes made to requests and assets

### PR DESCRIPTION
**Pull request by chandan5**

### CODE REVIEW

**Comment by gauravmittal1995** [comment]
@chandan5 or @nisargjhaveri , Please give a small explanation for the changes.

**Comment by chandan5** [comment]
There will be assets list with just name and description.
An organisation(organisation_id) can request for that asset which can be viewed publicly by other organisations and an organisation(supplier_id) can fulfill their request.

**Comment by gauravmittal1995** [comment]
LGTM!

**Comment by nisargjhaveri** [comment]
:+1:

**Pull request merged**
