### PR TITLE
Request supply and update working now

### PR DESCRIPTION
**Pull request by kartikgupta0909**
Now somebody add the GUI to the Update and supply views.

### CODE REVIEW

**Comment by gauravmittal1995** [comment]
Please don't add an extra update.php file to view. Refer to https://github.com/nisargjhaveri/saathi/pull/59 and follow this format for uniformity.

**Comment by gauravmittal1995** [comment]
Also please correct the indentation. There seems to be two different sets of indentation. Remove one.

**Comment by nisargjhaveri** [comment]
@kartikgupta0909, Please check you time settings for Git. Your commits are always from future! :P

**Comment by nisargjhaveri** [comment]
I think this one is outdated. see 4e81531267351c7bb7d71cf4c7caeb9f38cff899.

**Pull request closed without merging**
