### PR TITLE
Seperated the SQL dumps in a seperate folder

### PR DESCRIPTION
**Pull request by gauravmittal1995**
Basically, dumped all the dumps in a separate folder.
@imjalpreet @nisargjhaveri Please comment.

Should we do it or not?

### CODE REVIEW

**Comment by nisargjhaveri** [comment]
Absolutely we should do this.

My only problem is with the name `database`, seems a bit misguiding to me. But, I don't have any better alternatives too. Probably `setup` or something? What do you think?

**Comment by chandan5** [comment]
Suggestion: We should write a funstion in setup.sh to load this sample data.

**Comment by nisargjhaveri** [comment]
@chandan5, see #2.

**Comment by gauravmittal1995** [comment]
@chandan5 If you want, you can work on it. It can certainly help if it works

**Comment by chandan5** [comment]
@gauravmittal1995 okay :+1:

**Comment by gauravmittal1995** [comment]
@nisargjhaveri Even i had problem with `database` but couldnt think of anything better. `setup` doesnt convey whats in it exactly. sounds like setup scripts. how bout `dumps` ??

**Comment by gauravmittal1995** [comment]
@nisargjhaveri Ping ^

**Comment by nisargjhaveri** [comment]
`database` looks better to me than `dumps` :grin: 

Anyway, I'm fine with either of them. Decide.

**Comment by gauravmittal1995** [comment]
lets leave it as database

**Comment by nisargjhaveri** [comment]
:+1: Merging.

**Pull request merged**
