### PR TITLE
Add autocomplete widget

### PR DESCRIPTION
**Pull request by nisargjhaveri**

### CODE REVIEW

**Comment by nisargjhaveri** [comment]
I'll add example of usage soon.

**Comment by nisargjhaveri** [comment]
See https://github.com/nisargjhaveri/saathi/wiki/How-to-use-autocomplete-widget

**Comment by nisargjhaveri** [comment]
Also see https://github.com/nisargjhaveri/saathi/pull/39

**Comment by gauravmittal1995** [comment]
Looks Nice and works perfectly. Thanks :+1: Merged!!

**Pull request merged**
