### PR TITLE
Request Module (Delete)

### PR DESCRIPTION
**Pull request by gauravmittal1995**
Delete function for the requests module.

One Question. Right now in view of requests, the heading of each view is the organization name. Do we change it to "Asset_Name for Organization_Name"?? 
@imjalpreet @nisargjhaveri Thoughts??

### CODE REVIEW

**Comment by imjalpreet** [comment]
@gauravmittal1995 I didn't get what do you want to say?

**Comment by imjalpreet** [comment]
Ok I got it. Maybe we can change it.

**Comment by gauravmittal1995** [comment]
See the example in the modal popup.

**Comment by imjalpreet** [comment]
@gauravmittal1995 Just check once, The request is not getting deleted.

**Comment by gauravmittal1995** [comment]
@imjalpreet Can u check it now?

**Comment by imjalpreet** [comment]
Looks good to merge! :+1:

**Pull request merged**
