### PR TITLE
Updated Missing Person Details

### PR DESCRIPTION
**Pull request by viharpatel94**

### CODE REVIEW

**Comment by gauravmittal1995** [comment]
There seems to be some indentation error. Try setting it to similar indentation.

Also file modes are getting changed. @nisargjhaveri Does it matter?

Have'nt tried it yet, will do it tom

**Comment by gauravmittal1995** [comment]
Also you need to remove merge commits. Instead of merging, try rebasing.

**Comment by imjalpreet** [comment]
It is still not complete as when we click on update the form I got had empty fields even if there was data already in those fields in the db. For eg in my case the section Contact details of missing person was empty. If you need some kind of template you can have a look at #59 's update  function.

**Comment by nisargjhaveri** [comment]
Also, as @gauravmittal1995 mentioned, file modes should not be changed as 644 is good enough, there is not need to give execute permission on PHP files.

**Comment by gauravmittal1995** [comment]
To be completed in https://github.com/nisargjhaveri/saathi/pull/77

**Pull request closed without merging**
