### PR TITLE
Update Missing Person Details Added

### PR DESCRIPTION
**Pull request by sneakyironknight**

### CODE REVIEW

**Comment by imjalpreet** [comment]
I am getting a few errors just have a look at them.

update

**Comment by gauravmittal1995** [comment]
@sneakyironknight I am working on update for organisations. If u want to wait for 1 hour or so, it will be up and u can use that template for this

**Comment by sneakyironknight** [comment]
@imjalpreet actually added a connection to my db forgot to correct that
will update that

**Comment by imjalpreet** [comment]
@sneakyironknight Now there have been changes in the same files in which you have made changes, So please try to remove merge conflicts and update the pr.

**Comment by gauravmittal1995** [comment]
@sneakyironknight Status?

**Comment by gauravmittal1995** [comment]
Closing, to be completed in https://github.com/nisargjhaveri/saathi/pull/77

**Pull request closed without merging**
